jobs:
  login-to-azure:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    executor: azure-cli/azure-docker
    steps:
      - azure-cli/login-with-service-principal
      - run:
          command: az resource list
          name: List resources of tenant stored as `AZURE_SP_TENANT` env var
      - run:
          name: Install Azure functions tools
          command: |
            sudo apt install gnupg
            curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
            sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
            sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list'
            sudo apt-get update
            sudo apt-get install azure-functions-core-tools-3
      - run:
          name: Run 'func'
          command: func

orbs:
  azure-cli: circleci/azure-cli@1.0.0
version: 2.1
workflows:
  login-workflow:
    jobs:
      - login-to-azure
