jobs:
  login-to-azure:
    executor: azure-cli/azure-docker
    steps:
      - azure-cli/login-with-service-principal
      - run:
          command: az resource list
          name: List resources of tenant stored as `AZURE_SP_TENANT` env var
  install-function-tools:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Install Azure functions tools
          command: npm i -g azure-functions-core-tools@3 --unsafe-perm true
      - run:
          name: Run 'func'
          command: func

orbs:
  azure-cli: circleci/azure-cli@1.0.0
version: 2.1
workflows:
  login-workflow:
    jobs:
      - login-to-azure
      - install-function-tools:
          requires:
            - login-to-azure
